import turtle

mir = turtle.Turtle()
mir.penup()
mir.right(180)
mir.forward(240)
mir.right(90)
                                # m
mir.pendown()
mir.forward(150)
mir.right(155)
mir.forward(150)
mir.left(135)
mir.forward(145)
mir.right(160)
mir.forward(150)
                                # m
                                # i
mir.penup()
mir.left(90)
mir.forward(10)
mir.left(90)

mir.pendown()
mir.pencolor("red")
mir.forward(150)
mir.left(180)
mir.forward(150)
                                # i
                                # r
mir.penup()
mir.left(90)
mir.forward(10)
mir.left(90)

mir.pendown()
mir.pencolor("green")
mir.forward(150)
mir.right(90)
mir.forward(50)
mir.right(90)
mir.forward(50)
mir.right(90)
mir.forward(50)
mir.left(115)
mir.forward(110)
                                # r
                                # f
mir.penup()
mir.left(65)
mir.forward(15)
mir.left(90)

mir.pendown()
mir.pencolor("blue")
mir.forward(150)
mir.right(90)
mir.forward(50)
mir.right(180)
mir.forward(50)
mir.left(90)
mir.forward(50)
mir.left(90)
mir.forward(50)
mir.left(180)
mir.forward(50)
mir.left(90)
mir.forward(100)
                                # f
                                # a
mir.penup()
mir.left(90)
mir.forward(40)
mir.left(80)

mir.pendown()
mir.pencolor("blueviolet")
mir.forward(150)
mir.right(155)
mir.forward(150)
mir.right(180)
mir.forward(50)
mir.left(75)
mir.forward(45)
mir.right(180)
mir.forward(45)
mir.right(75)
mir.forward(50)
                                # a
                                # y
mir.penup()
mir.left(65)
mir.forward(15)
mir.left(70)

mir.pendown()
mir.pencolor("gold")
mir.forward(150)
mir.right(180)
mir.forward(80)
mir.right(125)
mir.forward(80)
mir.right(180)
mir.forward(80)
                                # y
                                # z
mir.penup()
mir.forward(70)
mir.left(65)
mir.forward(10)
mir.left(60)

mir.pendown()
mir.pencolor("blueviolet")
mir.forward(150)
mir.left(120)
mir.forward(70)
mir.right(180)
mir.forward(70)
mir.right(120)
mir.forward(150)
mir.left(120)
mir.forward(80)
                                # z
                                # chiziq
mir.penup()
mir.pencolor("fuchsia")
mir.right(90)
mir.forward(10)
mir.right(90)
mir.pendown()
mir.forward(480)
mir.penup()
mir.left(90)
mir.forward(10)
mir.left(90)
mir.forward(10)
mir.right(90)
mir.forward(150)
mir.right(180)
                                # chiziq
                                # m
mir.pendown()
mir.forward(150)
mir.right(155)
mir.forward(150)
mir.left(135)
mir.forward(145)
mir.right(160)
mir.forward(150)
                                # m
                                # i
mir.penup()
mir.left(90)
mir.forward(10)
mir.left(90)

mir.pendown()
mir.pencolor("blueviolet")
mir.forward(150)
mir.left(180)
mir.forward(150)
                                # i
mir.penup()
mir.left(90)
mir.forward(10)
mir.left(90)
                                # m
mir.pendown()
mir.pencolor("green")
mir.forward(150)
mir.right(155)
mir.forward(150)
mir.left(135)
mir.forward(145)
mir.right(160)
mir.forward(150)
                                # m
                                # i
mir.penup()
mir.left(90)
mir.forward(10)
mir.left(90)

mir.pendown()
mir.pencolor("yellow")
mir.forward(150)
mir.left(180)
mir.forward(150)
                                # i
                                # t
mir.penup()
mir.left(90)
mir.forward(70)
mir.left(90)

mir.pendown()
mir.pencolor("purple")
mir.forward(150)
mir.left(90)
mir.forward(60)
mir.right(180)
mir.forward(120)
mir.right(180)
mir.forward(60)
mir.left(90)
mir.forward(150)
                                # t
                                # o
# mir = turtle.Turtle()
# mir.speed(15)
# mir.pencolor(blueviolet)
# for i in range(180):
#     mir.forward(60)
#     mir.right(30)
#     mir.forward(20)
#     mir.left(60)
#     mir.forward(50)
#     mir.right(30)

# mir.penup()
# mir.left(90)
# mir.forward(70)
# mir.left(90)

# mir.pendown()

# mir.right(2)
# turtle.done()